name: Kubectl Test

on:
  workflow_dispatch:

jobs:

  kubectl-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
